-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgNhvDAdONm5vk+bEa
WvHBK6ovXXevG47ZsSHmGlScsgagCgYIKoZIzj0DAQehRANCAARqP/Clwbqocuhp
CMY9RyJTaj8McyOWea6vB0lhmf8Oc3df0DIV/4+OJLSgw68sGAkK3nLJDo+4rrZd
YFB5CViM
-----END PRIVATE KEY-----